import { getDb } from "../api/queries/connection";
import { categories, entrepreneurs, products, banners, news, communes } from "./schema";

async function seed() {
  const db = getDb();

  // Seed all 30 communes of Region del Maule
  const communeData = await db.insert(communes).values([
    { name: "Talca", province: "Talca" },
    { name: "San Clemente", province: "Talca" },
    { name: "Pelarco", province: "Talca" },
    { name: "Pencahue", province: "Talca" },
    { name: "Maule", province: "Talca" },
    { name: "San Rafael", province: "Talca" },
    { name: "Constitución", province: "Talca" },
    { name: "Curepto", province: "Talca" },
    { name: "Empedrado", province: "Talca" },
    { name: "Río Claro", province: "Talca" },
    { name: "Curicó", province: "Curico" },
    { name: "Hualañé", province: "Curico" },
    { name: "Licantén", province: "Curico" },
    { name: "Molina", province: "Curico" },
    { name: "Rauco", province: "Curico" },
    { name: "Romeral", province: "Curico" },
    { name: "Sagrada Familia", province: "Curico" },
    { name: "Teno", province: "Curico" },
    { name: "Vichuquén", province: "Curico" },
    { name: "Linares", province: "Linares" },
    { name: "Colbún", province: "Linares" },
    { name: "Longaví", province: "Linares" },
    { name: "Parral", province: "Linares" },
    { name: "Retiro", province: "Linares" },
    { name: "San Javier", province: "Linares" },
    { name: "Villa Alegre", province: "Linares" },
    { name: "Yerbas Buenas", province: "Linares" },
    { name: "Cauquenes", province: "Cauquenes" },
    { name: "Chanco", province: "Cauquenes" },
    { name: "Pelluhue", province: "Cauquenes" },
  ]).$returningId();

  // Seed categories
  const cats = await db.insert(categories).values([
    { name: "Alimentos", slug: "alimentos", icon: "🍯", description: "Productos alimenticios artesanales y gourmet" },
    { name: "Artesanía", slug: "artesania", icon: "🧶", description: "Textiles, cerámica y artesanías tradicionales" },
    { name: "Belleza", slug: "belleza", icon: "🧴", description: "Cosmética natural y productos de cuidado personal" },
    { name: "Turismo", slug: "turismo", icon: "🗺️", description: "Servicios turísticos y experiencias locales" },
    { name: "Tecnología", slug: "tecnologia", icon: "💻", description: "Servicios digitales y tecnológicos" },
    { name: "Moda", slug: "moda", icon: "👕", description: "Ropa, accesorios y diseño local" },
    { name: "Madera", slug: "madera", icon: "🪵", description: "Productos de carpintería y tallado en madera" },
    { name: "Vinos", slug: "vinos", icon: "🍷", description: "Vinos, licores y bebidas artesanales" },
  ]).$returningId();

  // Seed banners
  await db.insert(banners).values([
    {
      title: "Compra en el Comercio Local",
      subtitle: "Elige emprendimientos de maulinos para maulinos",
      image: "/images/banner-hero-1.jpg",
      link: "/emprendedores",
      position: "home_hero",
      order: 0,
      active: true,
    },
    {
      title: "¿Quieres unirte a la familia?",
      subtitle: "Sé parte de la vitrina de emprendedores más grande de la región",
      image: "/images/entrepreneur-join.jpg",
      link: "/unirse",
      position: "home_hero",
      order: 1,
      active: true,
    },
  ]);

  // Seed entrepreneurs - using real commune IDs
  const ents = await db.insert(entrepreneurs).values([
    {
      name: "Mermeladas Yerbas",
      slug: "mermeladas-yerbas",
      description: "Mermeladas artesanales elaboradas con frutas de la zona del Maule. Productos 100% naturales sin conservantes.",
      shortDescription: "Mermeladas artesanales naturales del Maule",
      logo: "/images/product-mermeladas.jpg",
      categoryId: cats[0].id,
      communeId: communeData[0].id, // Talca
      subcategory: "Conservas",
      region: "Maule",
      address: "1 Sur 848, Talca",
      phone: "+56912345678",
      whatsapp: "+56912345678",
      email: "contacto@mermeladasyerbas.cl",
      website: "https://mermeladasyerbas.cl",
      instagram: "@mermeladasyerbas",
      facebook: "https://facebook.com/mermeladasyerbas",
      status: "active",
      featured: true,
      views: 1250,
    },
    {
      name: "Artesanos de Chanco",
      slug: "artesanos-de-chanco",
      description: "Artesanía tradicional chilena con técnicas ancestrales. Textiles, cerámica y productos de mimbre.",
      shortDescription: "Artesanía tradicional con técnicas ancestrales",
      logo: "/images/product-artesanias.jpg",
      categoryId: cats[1].id,
      communeId: communeData[25].id, // Chanco
      subcategory: "Textiles",
      region: "Maule",
      address: "Calle Principal 123, Chanco",
      phone: "+56987654321",
      whatsapp: "+56987654321",
      email: "artesanos@chanco.cl",
      instagram: "@artesanoschanco",
      status: "active",
      featured: true,
      views: 980,
    },
    {
      name: "Miel del Maule",
      slug: "miel-del-maule",
      description: "Miel orgánica producida en los valles del Maule. Apicultura sustentable con respeto por la naturaleza.",
      shortDescription: "Miel orgánica de los valles del Maule",
      logo: "/images/product-miel.jpg",
      categoryId: cats[0].id,
      communeId: communeData[21].id, // San Javier
      subcategory: "Apicultura",
      region: "Maule",
      address: "Camino Rural Km 15, San Javier",
      phone: "+56923456789",
      whatsapp: "+56923456789",
      email: "miel@mieldelmaule.cl",
      instagram: "@mieldelmaule",
      status: "active",
      featured: false,
      views: 650,
    },
    {
      name: "Guías Turísticos del Maule",
      slug: "guias-turisticos-maule",
      description: "Tours personalizados por la región del Maule. Experiencias en viñedos, termas y parques naturales.",
      shortDescription: "Tours y experiencias turísticas en la región",
      logo: "/images/banner-hero-1.jpg",
      categoryId: cats[3].id,
      communeId: communeData[16].id, // Linares
      subcategory: "Tours",
      region: "Maule",
      address: "Av. Independencia 456, Linares",
      phone: "+56934567890",
      whatsapp: "+56934567890",
      email: "info@guiasmaule.cl",
      website: "https://guiasmaule.cl",
      instagram: "@guiasmaule",
      status: "active",
      featured: true,
      views: 720,
    },
    {
      name: "Cosmética Licantén",
      slug: "cosmetica-licanten",
      description: "Productos de belleza naturales y orgánicos elaborados con ingredientes locales del litoral maulino.",
      shortDescription: "Cosmética natural del litoral maulino",
      logo: "/images/product-artesanias.jpg",
      categoryId: cats[2].id,
      communeId: communeData[9].id, // Licantén
      subcategory: "Cosmética natural",
      region: "Maule",
      address: "Calle Costanera 78, Licantén",
      phone: "+56945678901",
      whatsapp: "+56945678901",
      email: "contacto@cosmeticalicanten.cl",
      instagram: "@cosmeticalicanten",
      status: "active",
      featured: false,
      views: 430,
    },
    {
      name: "Espíritu Emprendedor",
      slug: "espiritu-emprendedor",
      description: "Servicios de asesoría y capacitación para emprendedores de la región del Maule.",
      shortDescription: "Asesoría y capacitación para emprendedores",
      logo: "/images/entrepreneur-join.jpg",
      categoryId: cats[4].id,
      communeId: communeData[7].id, // Curicó
      subcategory: "Capacitación",
      region: "Maule",
      address: "Av. Camilo Henríquez 890, Curicó",
      phone: "+56956789012",
      whatsapp: "+56956789012",
      email: "hola@espirituemprendedor.cl",
      website: "https://espirituemprendedor.cl",
      instagram: "@espirituemprendedor",
      status: "active",
      featured: false,
      views: 380,
    },
    {
      name: "Viña Colinas del Maule",
      slug: "vina-colinas-maule",
      description: "Vinos artesanales producidos en las colinas del Maule. Experiencias de enoturismo y degustaciones.",
      shortDescription: "Vinos artesanales del Maule",
      logo: "/images/banner-hero-1.jpg",
      categoryId: cats[7].id,
      communeId: communeData[24].id, // Cauquenes
      subcategory: "Vinos",
      region: "Maule",
      address: "Ruta J-60 Km 25, Cauquenes",
      phone: "+56967890123",
      whatsapp: "+56967890123",
      email: "vinos@colinasdelmaule.cl",
      website: "https://colinasdelmaule.cl",
      instagram: "@colinasdelmaule",
      status: "active",
      featured: false,
      views: 890,
    },
    {
      name: "Madera Viva",
      slug: "madera-viva",
      description: "Carpintería artesanal con maderas nativas. Muebles, decoración y productos de madera sustentable.",
      shortDescription: "Carpintería artesanal con maderas nativas",
      logo: "/images/product-artesanias.jpg",
      categoryId: cats[6].id,
      communeId: communeData[18].id, // Longaví
      subcategory: "Carpintería",
      region: "Maule",
      address: "Calle Los Pinos 45, Longaví",
      phone: "+56978901234",
      whatsapp: "+56978901234",
      email: "contacto@maderaviva.cl",
      instagram: "@maderaviva",
      status: "active",
      featured: false,
      views: 510,
    },
    {
      name: "Dulces de Molina",
      slug: "dulces-de-molina",
      description: "Dulces tradicionales y confites artesanales de Molina. Recetas familiares transmitidas por generaciones.",
      shortDescription: "Dulces artesanales de Molina",
      logo: "/images/product-mermeladas.jpg",
      categoryId: cats[0].id,
      communeId: communeData[10].id, // Molina
      subcategory: "Dulces",
      region: "Maule",
      address: "Av. Balmaceda 234, Molina",
      phone: "+56989012345",
      whatsapp: "+56989012345",
      email: "dulces@demolina.cl",
      instagram: "@dulcesdemolina",
      status: "active",
      featured: false,
      views: 340,
    },
    {
      name: "Tejidos Villa Alegre",
      slug: "tejidos-villa-alegre",
      description: "Tejidos a mano con lana natural. Bufandas, gorros y mantas de alta calidad.",
      shortDescription: "Tejidos artesanales de lana natural",
      logo: "/images/product-artesanias.jpg",
      categoryId: cats[1].id,
      communeId: communeData[22].id, // Villa Alegre
      subcategory: "Tejidos",
      region: "Maule",
      address: "Calle Principal 56, Villa Alegre",
      phone: "+56990123456",
      whatsapp: "+56990123456",
      email: "tejidos@villaalegre.cl",
      instagram: "@tejidosvillaalegre",
      status: "active",
      featured: false,
      views: 280,
    },
    {
      name: "Cerveza Pencahue",
      slug: "cerveza-pencahue",
      description: "Cerveza artesanal producida en Pencahue con ingredientes locales. Variedades rubia, roja y negra.",
      shortDescription: "Cerveza artesanal de Pencahue",
      logo: "/images/product-miel.jpg",
      categoryId: cats[7].id,
      communeId: communeData[3].id, // Pencahue
      subcategory: "Cerveza artesanal",
      region: "Maule",
      address: "Camino a la Cervecería 12, Pencahue",
      phone: "+56901234567",
      whatsapp: "+56901234567",
      email: "cerveza@pencahue.cl",
      instagram: "@cervezapencahue",
      status: "active",
      featured: false,
      views: 410,
    },
    {
      name: "Panadería Constitución",
      slug: "panaderia-constitucion",
      description: "Pan artesanal de masa madre, kuchenes y empanadas horneadas diariamente en Constitución.",
      shortDescription: "Pan artesanal de masa madre",
      logo: "/images/product-mermeladas.jpg",
      categoryId: cats[0].id,
      communeId: communeData[6].id, // Constitución
      subcategory: "Panadería",
      region: "Maule",
      address: "Calle Comercio 89, Constitución",
      phone: "+56912345670",
      whatsapp: "+56912345670",
      email: "pan@constitucion.cl",
      instagram: "@panaderiaconstitucion",
      status: "active",
      featured: false,
      views: 360,
    },
  ]).$returningId();

  // Seed products
  await db.insert(products).values([
    {
      entrepreneurId: ents[0].id,
      name: "Mermelada de Frutilla",
      description: "Mermelada artesanal de frutillas de temporada, sin conservantes.",
      price: "$3.500",
      image: "/images/product-mermeladas.jpg",
      status: "active",
      featured: true,
      views: 320,
    },
    {
      entrepreneurId: ents[0].id,
      name: "Mermelada de Arándanos",
      description: "Deliciosa mermelada de arándanos del sur de Chile.",
      price: "$4.000",
      image: "/images/product-mermeladas.jpg",
      status: "active",
      featured: false,
      views: 180,
    },
    {
      entrepreneurId: ents[1].id,
      name: "Poncho de Lana",
      description: "Poncho tradicional tejido a mano con lana de oveja local.",
      price: "$45.000",
      image: "/images/product-artesanias.jpg",
      status: "active",
      featured: true,
      views: 250,
    },
    {
      entrepreneurId: ents[1].id,
      name: "Cesta de Mimbre",
      description: "Cesta tejida a mano con mimbre local, ideal para picnic.",
      price: "$15.000",
      image: "/images/product-artesanias.jpg",
      status: "active",
      featured: false,
      views: 120,
    },
    {
      entrepreneurId: ents[2].id,
      name: "Miel Orgánica 500g",
      description: "Miel pura de abejas criadas en los valles del Maule.",
      price: "$6.500",
      image: "/images/product-miel.jpg",
      status: "active",
      featured: true,
      views: 210,
    },
    {
      entrepreneurId: ents[2].id,
      name: "Propóleo Natural",
      description: "Extracto de propóleo para fortalecer el sistema inmune.",
      price: "$4.500",
      image: "/images/product-miel.jpg",
      status: "active",
      featured: false,
      views: 95,
    },
    {
      entrepreneurId: ents[6].id,
      name: "Vino Carménere",
      description: "Vino tinto artesanal de uvas Carménere cosechadas a mano.",
      price: "$12.000",
      image: "/images/banner-hero-1.jpg",
      status: "active",
      featured: true,
      views: 340,
    },
    {
      entrepreneurId: ents[6].id,
      name: "Vino Rosé",
      description: "Vino rosé fresco y frutal, ideal para días de verano.",
      price: "$10.000",
      image: "/images/banner-hero-1.jpg",
      status: "active",
      featured: false,
      views: 160,
    },
    {
      entrepreneurId: ents[8].id,
      name: "Kuchen de Nuez",
      description: "Kuchen tradicional con nueces de la zona.",
      price: "$5.500",
      image: "/images/product-mermeladas.jpg",
      status: "active",
      featured: false,
      views: 130,
    },
    {
      entrepreneurId: ents[10].id,
      name: "Cerveza Rubia Artesanal",
      description: "Cerveza rubia refrescante con notas cítricas.",
      price: "$3.200",
      image: "/images/product-miel.jpg",
      status: "active",
      featured: false,
      views: 170,
    },
  ]);

  // Seed news
  await db.insert(news).values([
    {
      title: "Market Maule brilló en Molina con emprendedores locales",
      slug: "market-maule-brillo-molina",
      excerpt: "La Plaza de Armas de Molina fue el escenario de una nueva versión de Market Maule.",
      content: "La Plaza de Armas de Molina fue el escenario de una nueva versión de Market Maule, donde artesanos y productores de la región se reunieron para mostrar sus productos. El evento contó con más de 50 emprendedores y una gran asistencia de público.",
      image: "/images/news-market.jpg",
      status: "published",
      views: 450,
      publishedAt: new Date("2025-04-15"),
    },
    {
      title: "Expo Market Maule deslumbró en Mall Go Florida",
      slug: "expo-market-maule-mall-go-florida",
      excerpt: "La feria reunió a decenas de pymes del Maule que pudieron mostrar sus productos.",
      content: "La feria reunió a decenas de pymes del Maule que pudieron mostrar sus productos en un espacio de alto tráfico. Los emprendedores destacaron la oportunidad de llegar a nuevos clientes.",
      image: "/images/news-market.jpg",
      status: "published",
      views: 380,
      publishedAt: new Date("2025-03-20"),
    },
    {
      title: "Nuevos emprendedores se unen a la familia Market Maule",
      slug: "nuevos-emprendedores-market-maule",
      excerpt: "Bienvenida a los nuevos emprendedores que se suman a la vitrina digital.",
      content: "Este mes damos la bienvenida a 12 nuevos emprendedores que se suman a nuestra vitrina digital. Productos desde mermeladas artesanales hasta servicios tecnológicos.",
      image: "/images/entrepreneur-join.jpg",
      status: "published",
      views: 290,
      publishedAt: new Date("2025-05-01"),
    },
    {
      title: "Feria de Emprendedores en Talca supera expectativas",
      slug: "feria-emprendedores-talca",
      excerpt: "Más de 5.000 visitantes asistieron a la feria de emprendedores en Talca.",
      content: "La feria de emprendedores realizada en el centro de Talca superó todas las expectativas con más de 5.000 visitantes durante el fin de semana. Los emprendedores reportaron ventas exitosas y nuevos contactos comerciales.",
      image: "/images/news-market.jpg",
      status: "published",
      views: 520,
      publishedAt: new Date("2025-04-28"),
    },
    {
      title: "Market Maule lanza nueva plataforma digital",
      slug: "market-maule-nueva-plataforma",
      excerpt: "La vitrina digital de emprendedores del Maule estrena nuevo sitio web.",
      content: "Market Maule estrena su nueva plataforma digital con mejoras en la experiencia de usuario, nuevas funcionalidades de búsqueda y un diseño moderno que facilita encontrar productos locales.",
      image: "/images/banner-hero-1.jpg",
      status: "published",
      views: 610,
      publishedAt: new Date("2025-05-05"),
    },
    {
      title: "Emprendedores de Cauquenes destacan en feria regional",
      slug: "emprendedores-cauquenes-feria",
      excerpt: "Productores de Cauquenes destacaron por la calidad de sus vinos y productos gourmet.",
      content: "Los emprendedores de Cauquenes destacaron en la feria regional por la calidad de sus vinos artesanales y productos gourmet. La provincia de Cauquenes se consolida como un polo de emprendimiento en la región del Maule.",
      image: "/images/entrepreneur-join.jpg",
      status: "published",
      views: 310,
      publishedAt: new Date("2025-03-10"),
    },
  ]);

  console.log("✅ Seed completed successfully!");
}

seed().catch(console.error);
